### ISSUE TITLE
- b and -f are not working

### ISSUE THREAD

**Issue by samaln** [tbrown91/SimBac#1]
Hello tbrown91, 

I am interested in simulating whole bacterial genomes with your tool to perform alignments. But in order to analyse them, I need the log files generated by the parameters -b and -f.

I tried the commands in the supplementary information. All works fine except from the exemple 2 and I get a core dumped error each time I tried to apply the -b (along with -R and -D ) and the - f (along with -r and -e).
Also, I get an error message saying that the /root is a denied access. 

Do you know where those errors may come from?

Thanks, 

Samaln

**Comment by tbrown91** [comment]
Hi Samaln,

I updated the log file written to include the break points and lineage of each interval, being either internal or external. This was included under the -b argument and I removed the -f argument. Unfortunately I forgot to update the accompanying pdf, so this is currently out of date.

Given the amount of information included in each node of the tree, this quickly becomes unscalable and when I try to run this on a large ARG (high internal or external recombination rate or large genome) I run out of RAM pretty quickly. This was designed for small-scale trees, but if you are desperate I could rewrite the original log file functions to output just the break-points of internal and external recombination events, without tracking the internal lineages.

As far as the /root denied access error, that is likely to be an issue with the permissions you have and that you give to programs you run. Either running as super user or seeding the program should avoid this error. 

Please let me know if you'd like anything else added to the code.

Tom

**Comment by tbrown91** [comment]
Hi Samaln,

I've reintroduced the -b and -f arguments as they were included before. I hope this addresses your issues. 

Tom
