### ISSUE TITLE
Code stalling when using -g flag

### ISSUE THREAD

**Issue by szhan** [tbrown91/SimBac#7]
I encountered this issue when trying to get the log file with the -g flag. See #6.

**Comment by tbrown91** [comment]
Hopefully fixed now https://github.com/tbrown91/SimBac/pull/8

**Comment by tbrown91** [comment]
thanks @szhan

**Comment by szhan** [comment]
Thanks @tbrown91 !

**Comment by szhan** [comment]
I think I understand what is happening now. The procedure in `Arg::outputBREAKS` doesn't scale well as the number and length of the fragments get larger. I mistook that it was stalling because of how. much faster it ran when not printing the events using `-g`.

**Comment by szhan** [comment]
Thank you again!
